### ISSUE TITLE
Garminuino-App doesn't work with Google Maps 10.9.2

### ISSUE THREAD

**Issue by Niklas04** [skyforcetw/Garminuino#10]
Hi,
I've updated Google Maps to Version 10.9.2 and Garminuino-App won't work anymore.
The HUD shows "Ok" but the navigation informations doesn't show up.

In the log I get the error "java.lang.NoSuchFieldException: No field mActions in class Landroid/app/Notification$BuilderRemoteViews; (declaration of 'android.app.Notification$BuilderRemoteViews' appears in /system/framework/framework.jar)"

I always try to figure out, where the problem could be.
The function 
         views.getClass() (processGoogleMapsNotification, NotificationMontitor.java)
doesn't get the class "android.widget.Remoteview" but get "android.app.Notification$BuilderRemoteViews".
In this class the Field "mActions" doesn't exist.

Don't have found any solution course of lack of experience.
I think Google made some changes to the structure of the notification.

**Comment by skyforcetw** [comment]
What is your version of Android?
I test Garminuino on my old phone runs 6.0 , it's works.
Does not test on 9.0(Pie).

**Comment by Niklas04** [comment]
I've tested it on Android Version 9 and 8.1.0.
Do you have already installed Google Maps Version 10.9.2?

**Comment by skyforcetw** [comment]
I guess the package name of notify is changing from com.google.android.app.maps to com.google.android.gm, I will test the new package name later.


![112129](https://user-images.githubusercontent.com/5211184/52536097-03df8980-2d91-11e9-8ef2-e89d9801a58b.jpg)

**Comment by Niklas04** [comment]
On my device the app shows still com.google.android.apps.maps

![screenshot_20190210-173005](https://user-images.githubusercontent.com/33813894/52536392-37eb8800-2d5a-11e9-8fcd-3e21295d5718.png)

**Comment by skyforcetw** [comment]
My mistake, I ignore the com.google.android.apps.maps is exist on my phone....

**Comment by skyforcetw** [comment]
The original parsing method is based on Reflection, it's means only works on some hypothesis of Notification object self.

I add new parsing method based on Notification's extra, this is more safety & official mechanism to got we want.
I prefer parse extra first, only when no extra exist, change to Reflection. 
Give me some time to modify the code.....

**Comment by skyforcetw** [comment]
Hi, I update code, it's works on gmap 10.9.2.
But there are some function is under-construction, so not release a new version(0.2.0) now.

**Comment by Niklas04** [comment]
Hi,
thanks for the quick fix.
I tested it and works all great with the new method - except showing the distance to turn.
I found the bug and will make a pull request.

Btw, nice new layout! Only the text size (option_text_size) is in my opinion too big, maybe 18sp or 20sp would be better.

**Comment by skyforcetw** [comment]
I think put a option to select text size is better ^^
