### ISSUE TITLE
Doesn't detect roundabout left exit.

### ISSUE THREAD

**Issue by RWeducation** [skyforcetw/Garminuino#13]
![screenshot_20190215-155956](https://user-images.githubusercontent.com/40080503/52852049-97241080-313d-11e9-9d7b-e45107b924c1.png)

as attached in the screenshot above, The code doesn't detect roundabout left exit arrow. All other arrows are detected as expected. 

can you explain the following bit of code so i can figure out by myself?

`private static Arrow getArrow(ArrowImage image) {
        Arrow foundArrow = Arrow.None;
        for (Arrow a : Arrow.values()) {
            int sad = image.getSAD(a.value);
            if (0 == sad) {
                String shortString = Short.toString(a.value);
                Log.d(TAG, "Recognize " + a.name() + " " + shortString);
                foundArrow = a;
                break;
            }
        }
        return foundArrow;
    }`

I'm using your latest code BTW.

Thanks.

**Comment by skyforcetw** [comment]
Hi
Because our country is left-hand drive , so I cannot drive circle like you. Therefore I cannot get the arrow you meet.
There are all arrow I got:
![image](https://user-images.githubusercontent.com/5211184/52873164-5356f880-3189-11e9-948f-9b73a7d4b697.png)

The arrow judgement has a little tricky. I capture all arrow I can see, store as a image, resize it to a 4x4 image, treat white & green as 1 & 0. Therefore one arrow can convert to  a 4x4 B&W arrow image.
Align arrow pixels data to one line, can get a 16 bits number, it's all Arrow.values() means.

The final thing is easy, just a 16 bit number comparing.

**Comment by skyforcetw** [comment]
Please download this release
https://github.com/skyforcetw/Garminuino/releases/tag/0.2.2

**Comment by Niklas04** [comment]
Hi,
I installed the new version and the navigation symbols should be displayed right again.

Had the issue that the symbol "Convergence" had been interpreted as Roundabout. Don't know wyh, but this didn't happend with the old notification catching method (by reflection).

With version 0.2.2 I didn't get any navigation symbol displayed. I didn't get sad==0, course the Arrow-Value don't passed correctly.
With Pull-Request #14 it should work

**Comment by RWeducation** [comment]
> Hi
> Because our country is left-hand drive , so I cannot drive circle like you. Therefore I cannot get the arrow you meet.
> There are all arrow I got:
> ![image](https://user-images.githubusercontent.com/5211184/52873164-5356f880-3189-11e9-948f-9b73a7d4b697.png)
> 
> The arrow judgement has a little tricky. I capture all arrow I can see, store as a image, resize it to a 4x4 image, treat white & green as 1 & 0. Therefore one arrow can convert to a 4x4 B&W arrow image.
> Align arrow pixels data to one line, can get a 16 bits number, it's all Arrow.values() means.
> 
> The final thing is easy, just a 16 bit number comparing.
> 
> I will add the arrow you meet later.

Makes sense. Thanks for the Explaination. anyways, as i just need to Display the arrow on an i2c oled display I can just convert the bitmap to ascii and send it to the arduino as it is.

Thanks.

**Comment by skyforcetw** [comment]
I am afraid of changing 4x4 to 5x5 is not divisible to the original picture, make it hard to recognize by 25bit number.

I need do some expreiments to verify it.

**Comment by skyforcetw** [comment]
> Hi,
> I installed the new version and the navigation symbols should be displayed right again.
> 
> Had the issue that the symbol "Convergence" had been interpreted as Roundabout. Don't know wyh, but this didn't happend with the old notification catching method (by reflection).
> 
> With version 0.2.2 I didn't get any navigation symbol displayed. I didn't get sad==0, course the Arrow-Value don't passed correctly.
> With Pull-Request #14 it should work
I am afraid of changing 4x4 to 5x5 is not divisible to the original picture, make it hard to recognize by 25bit number.

I need do some expreiments to verify it.

**Comment by skyforcetw** [comment]
> > Hi
> > Because our country is left-hand drive , so I cannot drive circle like you. Therefore I cannot get the arrow you meet.
> > There are all arrow I got:
> > ![image](https://user-images.githubusercontent.com/5211184/52873164-5356f880-3189-11e9-948f-9b73a7d4b697.png)
> > The arrow judgement has a little tricky. I capture all arrow I can see, store as a image, resize it to a 4x4 image, treat white & green as 1 & 0. Therefore one arrow can convert to a 4x4 B&W arrow image.
> > Align arrow pixels data to one line, can get a 16 bits number, it's all Arrow.values() means.
> > The final thing is easy, just a 16 bit number comparing.
> > I will add the arrow you meet later.
> 
> Makes sense. Thanks for the Explaination. anyways, as i just need to Display the arrow on an i2c oled display I can just convert the bitmap to ascii and send it to the arduino as it is.
> 
> Thanks.

For your purpose, as you say, can pass the recognize of arrow, just do a simple bitmap converting.

**Comment by skyforcetw** [comment]
I collect all roundabout as I can , put at 
https://github.com/skyforcetw/Garminuino/tree/master/GoogleMap_Arrow_Recognize/PatternRecognize/workdir/Google_Arrow2

If any new arrow of roundabout I miss, please let me know as a issue.
