### ISSUE TITLE
Is it just me or the code for notification listener and bluetooth part doesn't exist in the source?

### ISSUE THREAD

**Issue by RWeducation** [skyforcetw/Garminuino#2]

**Comment by Niklas04** [comment]
Yes, somehow this part of the app is missing.
If you are looking into the [source code of version 0.1.2](https://github.com/skyforcetw/Garminuino/tree/0.1.2/GoogleMaps_HUD) the the part exists.

It seems that in version 0.1.2 the parsing of the notification isn't working correctly. In version 0.1.4 it seems to work (nearly) correct.

Niklas

**Comment by skyforcetw** [comment]
I will upload the completed code later, some code I forgot to upload.

**Comment by skyforcetw** [comment]
Hi, I upload the complete code, please sync & compile again.

**Comment by RWeducation** [comment]
got the code thanks!
