### ISSUE TITLE
No issue just talking

### ISSUE THREAD

**Issue by Adim01** [skyforcetw/Garminuino#20]
I got no problem with your app, is just wanted to say thank you!
I bought the Garmin HUD 6 month before the end of its life (Garmin pulling the plug on all apps),

I was ready throwing it away but luckily forgot.

Today I found it and were curious if there was any other way for it to work, and then I found you and your app using Google maps my since then preferred navigation system.

I am really grateful for what you are doing here because i really liked the concept of the HUD ad the vastly superiority of Google Maps.

IMHO I hope you will add some more features, like for example the lane pointer under the arrows.

But for now this app is really great and I hope you will support it for a long time and maintaining it.

**Comment by skyforcetw** [comment]
Hi

Thanks for your comment.
Hope it can help you driving right direction ^^

Yes , I think the lane pointer is very important, I'm working on it.

**Comment by skyforcetw** [comment]
Hi 
I add  lane pointer in 0.4.4
You can download & test it:
https://github.com/skyforcetw/Garminuino/releases/download/0.4.4/gmaps_hud-release_v0.4.4.apk
