### ISSUE TITLE
Google maps HUD keeps stopping

### ISSUE THREAD

**Issue by chaminda81** [skyforcetw/Garminuino#21]
Hi 
I don't' have the garmin HUD but wanted to test the app itself to see if it works. 
The app loads fine but as soon as I try to navigate with googe maps I get the error "Google maps HUD keeps stopping"
I'm using a moto g5s with android 8.1
Thanks

**Comment by skyforcetw** [comment]
Hi, this app have two part: recognize gmap & send to garmin hud.
I can turn off sending part, when no garmin hud linked.

But why do you want to test the app without garmin hud?

**Comment by chaminda81** [comment]
Hi 
I wanted to test the App before I bought the HUD. Shouldn't it still work without the HUD? I.e not crash?

I was also wondering if your app could be recoded to support the arduino HUD
https://www.sparkfun.com/products/15079
The garmin HUD is difficult to find and it might be easier to use arduino based one
Thanks

**Comment by skyforcetw** [comment]
Ok, I would handle this.

Btw, sparkfun's hud seems great, if it is visible under sunlight, should be good！

**Comment by skyforcetw** [comment]
> Hi
> I wanted to test the App before I bought the HUD. Shouldn't it still work without the HUD? I.e not crash?
> 
> I was also wondering if your app could be recoded to support the arduino HUD
> https://www.sparkfun.com/products/15079
> The garmin HUD is difficult to find and it might be easier to use arduino based one
> Thanks

Hi
please try 0.4.1, should be work when no hud connected.
https://github.com/skyforcetw/Garminuino/releases/tag/0.4.1

BTW, do you have sparkfun's hud? I want to support it.
Maybe I can create a bridge, then this app can works with GarminHUD & Sparkfun HUD.

**Comment by skyforcetw** [comment]
Please re-download the apk & install.
I forgot to signed the apk, so cannot install on phone.
