### ISSUE TITLE
Android auto - Getting app to work when connected

### ISSUE THREAD

**Issue by chaminda81** [skyforcetw/Garminuino#22]
Hi
Is there any way this app can work when the phones is connected to an android auto head unit?
Thanks

**Comment by skyforcetw** [comment]
I dont have  android auto（AA）.
But someone had  told me, if notify is still popup when AA connected, this app can work.

**Comment by skyforcetw** [comment]
![P_20200130_112241](https://user-images.githubusercontent.com/5211184/73504861-c2197a00-440b-11ea-8987-7e6940b2805e.jpg)
Hi
The app can works with android auto.
