### ISSUE TITLE
New arrows cannot recognize

### ISSUE THREAD

**Issue by skyforcetw** [skyforcetw/Garminuino#26]
Gmaps update the arrows for easy verifying（My guessing）, the app cannot recognize arrows now. 

I will collect new arrows for recognizing someday.

**Comment by skyforcetw** [comment]
Hi!

Does any one know how to find the arrow of right to leave(or left to leave) ??

https://github.com/skyforcetw/Garminuino/raw/master/GoogleMap_Arrow_Recognize/PatternRecognize/workdir/Google_Arrow2/RightToLeave.png

**Comment by Niklas04** [comment]
I tried some places but didn't found the arrow.
Maybe it have been replaced with the Right or Keep Right arrow.

**Comment by skyforcetw** [comment]
Ok.... 
Let us forgot the these arrows !

**Comment by skyforcetw** [comment]
The arrows v2 I collected place here:
https://github.com/skyforcetw/Garminuino/blob/master/GoogleMaps_HUD/SUPPORTED_ARROWSv2.md

**Comment by skyforcetw** [comment]
Still some arrows failed, it's need some new method to recognize arrows.
