### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by Niklas04** [skyforcetw/Garminuino#28]
Hi,

I'm having the problem that the app keeps crashing when Google Maps Navigation is running and GoogleMaps HUD App is not running.
The app keeps crashing every 30 seconds until I end the navigation.
If I start the GoogleMaps HUD App everything works fine.

I was able to get the following log via Android Studio:
![Unbenannt](https://user-images.githubusercontent.com/33813894/72532123-1ef52c00-3873-11ea-83b9-c5f0ab952182.PNG)

Maybe you clue where the issue can be and fix it.

Best regards
Niklas

**Comment by skyforcetw** [comment]
Got it.
It seems only crash on android 10 ?

**Comment by skyforcetw** [comment]
I found the problem. My fault....

**Comment by skyforcetw** [comment]
Please try this one
https://github.com/skyforcetw/Garminuino/releases/tag/0.5.6

**Comment by Niklas04** [comment]
Thank you!
Seems to work
