### ISSUE TITLE
Android App won't work with my device

### ISSUE THREAD

**Issue by Niklas04** [skyforcetw/Garminuino#3]
Hi,
I've got a Garmin HUD and want to to use it with Google Maps.
I've downloaded your app but unfortunately it don't display any navigation information on the HUD.

Paring with the HUD and reading(/parsing) notification work with my device.

I've already tryed to import the code in Android Studio to get further debug information, but the main part of the app is missing.

My device is a Google Pixel 2 running Android 8.1.0. Language is set to German (but tried already with english language).

May you can figure out, what the issue is.
If I could help you somehow, it would be a pleasure.

Niklas

Somehow can't attach a picture, displayed Maps notification is:
LeaveRoundaboutUp 110 m 0:9 9,3 km Ankunft ca. 22:39 (period: 1280)

**Comment by Niklas04** [comment]
I solved the issue for myself. I took the source code of version 0.1.2 and looked for the issue(s).

The main problem was, that [one](https://github.com/skyforcetw/Garminuino/blob/645bc2546994a3b323068eca91c2639aa40ef04d/GoogleMaps_HUD/app/src/main/java/com/example/notificationlistenerdemo/NotificationMonitor.java#L433) String that is essentaelly needed for working, has to be translated into the language each phone is using.
The app is looking in the notification content of the Google Maps Notification for the keyword "EXIT NAVIGATION". Based on the keyword the app assign the individual sections of the notification.

Another problem was, that the notification hasn't been parsed correctly. Curiously there were some spaces between distance and distance unit, that shouldn't been there according to the code.
Another issue was the decimal seperator. In some countries (like in Germany) we use a comma to seperate the decimal. The Garmin HUD need the distance with a point seperated the decimals.

**Comment by wokawoka** [comment]
Any chance that you could share the compiled apk with us?
Many thanks

**Comment by skyforcetw** [comment]
The biggest bug of Garminuino is language difference.
I had meet the problem many times.
The app is involving with localization mechanism, this can solve part of this problem.

But different language/country setting can lead different format of navigation message. 
NEED EVERYBODY'S HELPING.

If you cannot run app work well, try switch to english language first, if it works....
A Language problem, again....

**Comment by wokawoka** [comment]
@Niklas04 - many thanks! I'll try switching to German for a test and see

**Comment by Niklas04** [comment]
@skyforcetw looked and played a little bit through the source-code. I think I understand, what you mean with problems caused by language differences.
But I think there are some other bugs, too.

Maybe I can try to help you, to get the app working for most/some languages. Will make a pull request withing the next days.

@wokawoka ok, I'l be exited to hear from you

**Comment by Niklas04** [comment]
This issue is solved for me.
Found the issues and shared it in Pull request #4 and #5 

@wokawoka may you can try version 0.1.5 (included #4) or:
https://drive.google.com/open?id=1oy-jPLDcT8L-3BwEeLw-UagneFjBjQAU (included #4 and #5)

If that issue isn't fixed for you, feel free to reopen.

Niklas
