### ISSUE TITLE
The App crashes

### ISSUE THREAD

**Issue by Joern80** [skyforcetw/Garminuino#31]
Hi!

First, I really like your Idea of bringing the Garmin Hud back to life and sync it with Google Maps!

But i can't get it to work... Perhaps you can help me? I tryied severel App-Versions but the problem is always the same: the first time, i run the app after installation, i'm able to connect the hud and everything seems to work fine. But if i want to reconnect the hud, the hud doesn't connect automaticaly. And if i want to open the app to reconnect it manually, the app keeps crashing. The only solution i found, is to delete the storage of the app and set everything up from the beginning. Again, everything is working... Until the next reconnect.

I'm using your app on a Pixel 2 with Android 10 in german language.

I hope you understand what i'm writing, my english is not the best 😉

**Comment by skyforcetw** [comment]
Hi, what is the newest version you try？
I had meet this problem in older version, but fix it after 0.6.3.

**Comment by Joern80** [comment]
I tried 0.6.4, 0.6.3 and also older versions.

**Comment by Joern80** [comment]
I played around with the problem... maybe it can help?

I figured out, that the app only crashes, when i reopen the app by clicking on the icon. If i open the app by clicking on the recent-app-list, there is no crash. But when i press the Bluetooth-reset-button, the app crashes immediately.

Once the garmin hud is powered off and on, it doesn't reconnect automatically. I can connect it manually by open the app like described above and connect it over the search-device-button. Sometimes i have to try it 2 or three times, but then it connects.

**Comment by skyforcetw** [comment]
Hi

I disable the BT init procedure when app start.
Hopes this can find bugs out. 

When you start app, touch "RESET BLUETOOTH" to init BT  ( If app didn't crash).
Then use app as previous.

**Comment by Niklas04** [comment]
Hi,
I tried to reproduce the issue on my device but didn't have any success.
On my device is installed version 0.6.4 and it runs fine.

Same requirements as @Joern80: Google Pixel 2 and german language

Strange issue

**Comment by Joern80** [comment]
I tried the versions 0.6.5 and 0.6.6

0.6.5:
The first time i open the app after installation, everything works fine. I press "reset Bluetooth" and can make a connection over the "connect device". After turning the hud off and on, the app doesn't connect automatically.  Pressing the "Bluetooth reset" leads into a crash. If i don't press "reset", just pressing "connect device", the app tells me, it is connected to the hud, but in fact, it isn't.

0.6.6:
The same behaviour like 0.6.5

The difference between 0.6.4 and 0.6.5/0.6.6: I'm able to open the app by pressing the app icon.

@Niklas04 : your comment makes me hope! 😀 Whats the difference between our devices? I'm using apps, that have notification access: ifttt, tasker, auto notification, notification listener... I tried to turn off the access to notification for these apps, but nothing changed.

**Comment by Niklas04** [comment]
Yes, that is a good question, what the difference might be ...

I don't think it is an issue regarding the notifications, I think it might be an issue with Bluetooth connection functionality.

Did you try to start the app without Google Maps running? If the app keeps crashing nevertheless, this should completely exclude worries regarding notification - I think.

I didn't try to turn off Garmin HUD while navigation is running. I will try that. Maybe it loses Bluetooth connection and this is causing some weird issue.

Running an app from the app icon and recent app list shouldn't make a difference, in my opinion.

**Comment by Joern80** [comment]
> Did you try to start the app without Google Maps running?

Yes, it doesn't matter, if maps is running or not.

> I didn't try to turn off Garmin HUD while navigation is running.

Most of the time i turn off the hud while no navigation is running.

Again I played around with 0.6.4. At first i reset the network settings (including Bluetooth). Nothing changed. 

After connecting the hud for the first time, a press on "reset Bluetooth" leads to a crash. It doesn't matter, if the hud is on or off. 

I didn't mentioned it before, I don't know it's important or not: after installing the app, the app wants me to enable the notification access. When I enable the access and go back, the app again wants me to enable the access. Everytime I ignored this because the notification access works fine.

**Comment by skyforcetw** [comment]
Hi 
Because of I don't have pixel 2 and not face this bug, all I can do is try&error.
Please try this v0.6.7
https://github.com/skyforcetw/Garminuino/releases/download/0.6.7/gmaps_hud-release_v0.6.7.apk

I think there is something wrong after first HUD connecting.
So I stop the most relative part to see is anything change.

**Comment by Joern80** [comment]
0.6.7:
First connection works fine. The second connecting leads to a problem: Again, no automatical connection. When i press "search device", my phone says "Bluetooth is not available". If i press "reset Bluetooth", the app crashes. But I'm able to reopen the app by clicking the icon without a crash.

I'm still wondering, that Niklas has no problem with his pixel 2. Should i make a factory reset on my phone?

**Comment by Niklas04** [comment]
I think it might be another app, that causes the issue.

Maybe you can try to press "Force stop" on different apps (only one at a time) and then reopen the GoogleMaps HUD App and test if it crashes. (I don't know how long an app stops before it restarts itself.)

Another way might be to uninstall some apps that might have some extended functionality (e.g. Tasker)

**Comment by skyforcetw** [comment]
Niklas04 should be right.

There is something change with Joern80's pixel2 bluetooth.
I modified the BT init procedure just like first time open the app in anytime.
Please try this one:
https://github.com/skyforcetw/Garminuino/releases/download/0.6.8/gmaps_hud-release_v0.6.8.apk

**Comment by Joern80** [comment]
I'm a little busy but at the end of the week i will test 0.6.8. If it doesn't work, i will check some apps and force them to stop... And if this doesn't help, i will reset my phone.

**Comment by Joern80** [comment]
I think I got a solution: it seems like the app "Flic" (Bluetooth Buttons) causes the problem. I'm not 100% sure, but when I delet the buttons in the Android Bluetooth Settings, the app don't forget the buttons, but the HUD app doesn't crash anymore.

**Comment by skyforcetw** [comment]
I will install "Flic" and try. 
Thanks for your information.

**Comment by skyforcetw** [comment]
Unfortunately , I don't have Flic's hardware, cannot meet the same issue.
