### ISSUE TITLE
Android version dependent?

### ISSUE THREAD

**Issue by greymda** [skyforcetw/Garminuino#35]
What Android version is compatible the project? 5+ or...?

**Comment by skyforcetw** [comment]
I am not sure compatible android version, but I remember andriod 6.0 up are ok.

**Comment by greymda** [comment]
> I am not sure compatible android version, but I remember andriod 6.0 up are ok.

that's odd. i'm on Android 6.0 (Huawei P8 Lite) and the "Notification Capture" button is OFF, then after a minute or two it changes to ON but later it can either go OFF by itself or the app just closes altogether :(
