### ISSUE TITLE
Speed won't show on the HUD

### ISSUE THREAD

**Issue by Niklas04** [skyforcetw/Garminuino#6]
For anyone having the same issue:

The speed won't be displayed on the HUD.

I think I found the issue, but want to test it (completly), before creating a new Pull request.

Niklas

**Comment by skyforcetw** [comment]
Look forward to your pull request.

I am focus on another IoT project, we dont have enough time XD

**Comment by Niklas04** [comment]
Yes, same here. Don't have enough time for all that stuff I want to do XD
